"""Built-in plugin list."""

BUILTIN_PLUGINS = [
	"pgml_lint.plugins.block_markers",
	"pgml_lint.plugins.pgml_heredocs",
	"pgml_lint.plugins.document_pairs",
	"pgml_lint.plugins.block_rules",
	"pgml_lint.plugins.pgml_required_macros",
	"pgml_lint.plugins.macro_rules",
	"pgml_lint.plugins.pgml_inline",
	"pgml_lint.plugins.pgml_inline_pgml_syntax",
	"pgml_lint.plugins.pgml_inline_braces",
	"pgml_lint.plugins.pgml_blanks",
	"pgml_lint.plugins.pgml_underscore_emphasis",
	"pgml_lint.plugins.pgml_brackets",
	"pgml_lint.plugins.pgml_blank_assignments",
	"pgml_lint.plugins.pgml_label_dot",
	"pgml_lint.plugins.pgml_ans_style",
	"pgml_lint.plugins.pgml_text_blocks",
	"pgml_lint.plugins.pgml_html_in_text",
	"pgml_lint.plugins.pgml_html_forbidden_tags",
	"pgml_lint.plugins.pgml_html_div",
	"pgml_lint.plugins.pgml_span_interpolation",
	"pgml_lint.plugins.pgml_style_string_quotes",
	"pgml_lint.plugins.pgml_ans_rule",
	"pgml_lint.plugins.pgml_br_variable",
	"pgml_lint.plugins.pgml_modes_html_escape",
	"pgml_lint.plugins.pgml_old_answer_checkers",
	"pgml_lint.plugins.pgml_solution_hint_macros",
]
